### ISSUE TITLE
pip2arch: pipy requires https

### ISSUE THREAD

**Issue by Anaphory** [Daenyth/pkgtools#57]
I just thought I might give pip2arch a try, but out of the box the program terminates with

```
Traceback (most recent call last):
  File "/sbin/pip2arch", line 251, in <module>
    main()
  File "/sbin/pip2arch", line 235, in main
    version=args.version, outname=args.outname)
  File "/sbin/pip2arch", line 61, in get_package
    versions = self.client.package_releases(name)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1167, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>
```

**Comment by Daenyth** [comment]
It looks like this is somewhat of an upstream bug at @bluepeppers. I'll put in a PR

**Comment by Daenyth** [comment]
Looks like it's already fixed actually and I just need to update the submodule
